queue:
  name: Hosted VS2017
  demands: msbuild

variables:
  DeploySiteName: 'AzureFunctionsIntroduction'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:
- task: DotNetCoreCLI@1
  inputs:
    command: "restore"
    projects: 'v2/**/*.sln'

- task: MSBuild@1
  inputs:
    solution: 'v2/**/*.sln'
    msbuildArchitecture: 'x64'
    msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\$(DeploySiteName).zip" /p:DeployIisAppPath=$(DeploySiteName)'

- task: AzureRmWebAppDeployment@3
  inputs:
    ConnectedServiceName: "AzureResourceManager"
    WebAppName: "$(DeploySiteName)"
    Package: '$(build.artifactstagingdirectory)/**/$(DeploySiteName).zip'

- task: PublishSymbols@1
  inputs:
    SearchPattern: 'v2/**/bin/**/*.pdb'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: "drop"
    ArtifactType: 'Container'
