queue:
  name: Hosted VS2017
  demands: msbuild

steps:
- task: DotNetCoreCLI@1
  inputs:
    command: "restore"
    projects: "v2/src/AzureFunctionsIntroduction.sln"

- task: MSBuild@1
  inputs:
    solution: "v2/src/AzureFunctionsIntroduction.sln"
    configuration: "Release"
    msbuildArguments: "/p:OutputPath=$(Build.SourcesDirectory)/Tmp"
    clean: "true"

- task: CmdLine@1
  inputs:
    filename: "C:/Program Files/IIS/Microsoft Web Deploy V3/msdeploy.exe"
    arguments: "-verb:sync -source:contentPath=$(Build.SourcesDirectory)/Tmp -dest:contentPath='$(DeploySiteName)',ComputerName='$(DeployScmUrl)',UserName='$(DeployUserName)',Password='$(DeployPassword)',AuthType='Basic'"
